import { useCallback, useEffect, useMemo, useState } from "react";
import { useParams, useSearchParams } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client-selfhosted";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "sonner";
import { CalendarDays, ChevronLeft, ChevronRight, Clock, Loader2, MapPin, Send, ShieldCheck } from "lucide-react";
import { fmtPhoneBR, isValidBRPhone, normalizeBRPhone } from "@/lib/phone-utils";

type PubEvent={id:string;titulo:string;inicio_em:string;fim_em:string;local:string|null;descricao:string|null;status:string;mensagem_cancelamento:string|null};
const pad=(n:number)=>String(n).padStart(2,"0"), ymd=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const pretty=(d:Date)=>d.toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long"});
const tm=(s:string)=>new Date(s).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"});

export default function AgendaPublica(){
  const {clientSlug}=useParams<{clientSlug:string}>(); const [qs]=useSearchParams();
  const initial=qs.get("data")&&/^\d{4}-\d{2}-\d{2}$/.test(qs.get("data")!)?new Date(`${qs.get("data")}T12:00:00`):new Date();
  const [cursor,setCursor]=useState(initial),[view,setView]=useState<"semana"|"mes">("semana"),[info,setInfo]=useState<any>(null),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[sending,setSending]=useState(false);
  const [form,setForm]=useState({nome:"",telefone:"",email:"",data:ymd(initial),inicio:"09:00",fim:"10:00",assunto:"",descricao:"",modalidade:"presencial",local:"",quantidade:""});
  const range=useMemo(()=>{if(view==="mes")return [new Date(cursor.getFullYear(),cursor.getMonth(),1),new Date(cursor.getFullYear(),cursor.getMonth()+1,1)];const s=new Date(cursor);s.setDate(s.getDate()-((s.getDay()+6)%7));s.setHours(0,0,0,0);const e=new Date(s);e.setDate(e.getDate()+7);return[s,e]},[cursor,view]);
  const load=useCallback(async()=>{if(!clientSlug)return;setLoading(true);const {data,error}=await supabase.rpc("agenda_publica" as any,{_slug:clientSlug,_inicio:range[0].toISOString(),_fim:range[1].toISOString()});if(error)setInfo({ok:false});else{setInfo(data);if((data as any)?.visualizacao_padrao&&info===null)setView((data as any).visualizacao_padrao)}setLoading(false)},[clientSlug,range[0].getTime(),range[1].getTime()]);
  useEffect(()=>{load()},[load]); useEffect(()=>{document.title=info?.nome?`Agenda de ${info.nome}`:"Agenda pública"},[info]);
  const events=(info?.eventos||[]) as PubEvent[];
  const days=useMemo(()=>{if(view==="semana")return Array.from({length:7},(_,i)=>{const d=new Date(range[0]);d.setDate(d.getDate()+i);return d});const first=new Date(cursor.getFullYear(),cursor.getMonth(),1),off=(first.getDay()+6)%7,n=new Date(cursor.getFullYear(),cursor.getMonth()+1,0).getDate();return Array.from({length:42},(_,i)=>{const x=i-off+1;return x>0&&x<=n?new Date(cursor.getFullYear(),cursor.getMonth(),x):null})},[range,view,cursor]);
  async function submit(){if(!clientSlug)return;if(form.nome.trim().length<3)return toast.error("Informe seu nome completo.");const tel=normalizeBRPhone(form.telefone);if(!isValidBRPhone(tel))return toast.error("Informe um WhatsApp válido com DDD.");if(form.assunto.trim().length<3)return toast.error("Explique o assunto do compromisso.");const ini=new Date(`${form.data}T${form.inicio}:00`),fim=new Date(`${form.data}T${form.fim}:00`);if(ini<=new Date())return toast.error("Escolha uma data e horário futuros.");if(fim<=ini)return toast.error("O horário final deve ser depois do inicial.");setSending(true);const {data,error}=await supabase.rpc("agenda_solicitar" as any,{_slug:clientSlug,_nome:form.nome.trim(),_telefone:tel,_email:form.email||null,_assunto:form.assunto.trim(),_descricao:form.descricao||null,_inicio:ini.toISOString(),_fim:fim.toISOString(),_modalidade:form.modalidade,_local:form.local||null,_quantidade:form.quantidade?Number(form.quantidade):null});setSending(false);if(error||!(data as any)?.ok)return toast.error("Não foi possível enviar. Confira os dados e tente novamente.");setOpen(false);toast.success(`Solicitação enviada! Protocolo: ${(data as any).protocolo}`,{duration:9000});}
  if(loading&&!info)return <div className="min-h-screen grid place-items-center"><Loader2 className="animate-spin"/></div>;
  if(!info?.ok)return <div className="min-h-screen grid place-items-center p-4 bg-muted/30"><Card className="max-w-md text-center"><CardHeader><CalendarDays className="mx-auto w-10 h-10 text-muted-foreground"/><CardTitle>Agenda indisponível</CardTitle><CardDescription>Este link não existe ou a página foi desativada temporariamente.</CardDescription></CardHeader></Card></div>;
  return <div className="min-h-screen bg-muted/30 pb-16"><header className="bg-white dark:bg-card border-b"><div className="max-w-6xl mx-auto p-4 md:p-6 flex items-center justify-between gap-4"> <div className="flex items-center gap-3">{info.logo_url&&<img src={info.logo_url} className="w-14 h-14 object-contain rounded-lg"/>}<div><h1 className="text-xl md:text-2xl font-bold">{info.titulo}</h1><p className="text-sm text-muted-foreground">{info.nome}</p></div></div><Button onClick={()=>setOpen(true)} style={{backgroundColor:info.cor}}><Send className="w-4 h-4 mr-2"/>Solicitar horário</Button></div></header>
    <main className="max-w-6xl mx-auto p-4 md:p-6 space-y-4"><p className="text-muted-foreground">{info.descricao}</p><Card><CardHeader className="pb-3"><div className="flex flex-wrap justify-between items-center gap-3"><div className="flex items-center gap-1"><Button variant="outline" size="icon" onClick={()=>{const d=new Date(cursor);view==="mes"?d.setMonth(d.getMonth()-1):d.setDate(d.getDate()-7);setCursor(d)}}><ChevronLeft/></Button><Button variant="outline" onClick={()=>setCursor(new Date())}>Hoje</Button><Button variant="outline" size="icon" onClick={()=>{const d=new Date(cursor);view==="mes"?d.setMonth(d.getMonth()+1):d.setDate(d.getDate()+7);setCursor(d)}}><ChevronRight/></Button></div><CardTitle className="capitalize text-lg">{view==="mes"?cursor.toLocaleDateString("pt-BR",{month:"long",year:"numeric"}):`${range[0].toLocaleDateString("pt-BR")} a ${new Date(range[1].getTime()-86400000).toLocaleDateString("pt-BR")}`}</CardTitle><div><Button size="sm" variant={view==="semana"?"default":"outline"} onClick={()=>setView("semana")}>Semana</Button><Button size="sm" variant={view==="mes"?"default":"outline"} onClick={()=>setView("mes")} className="ml-1">Mês</Button></div></div></CardHeader><CardContent>{view==="mes"&&<div className="grid grid-cols-7 text-center text-xs font-medium text-muted-foreground mb-2">{["Seg","Ter","Qua","Qui","Sex","Sáb","Dom"].map(x=><span key={x}>{x}</span>)}</div>}<div className={view==="mes"?"grid grid-cols-7 gap-1":"grid md:grid-cols-7 gap-2"}>{days.map((d,i)=>d?<div key={i} className={`rounded-lg border bg-background p-2 ${view==="mes"?"min-h-24":"min-h-44"}`}><div className="text-xs font-semibold capitalize mb-2">{view==="semana"?pretty(d):d.getDate()}</div>{events.filter(e=>ymd(new Date(e.inicio_em))===ymd(d)).map(e=><div key={e.id} className={`rounded-md p-2 mb-1 text-xs ${e.status==="cancelado"?"bg-red-100 text-red-800":"bg-primary/10"}`}><b>{tm(e.inicio_em)} · {e.titulo}</b>{e.local&&<div><MapPin className="inline w-3 h-3"/> {e.local}</div>}{e.status==="cancelado"&&<div className="font-bold">CANCELADO</div>}</div>)}</div>:<div key={i}/>)}</div></CardContent></Card><div className="text-center text-xs text-muted-foreground"><ShieldCheck className="inline w-4 h-4 mr-1"/>A agenda pode sofrer alterações. Consulte sempre esta página para informações atualizadas.</div></main>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-2xl max-h-[92vh] overflow-y-auto"><DialogHeader><DialogTitle>Solicitar um horário</DialogTitle><DialogDescription>Seu pedido será analisado pela equipe. O horário só estará confirmado depois da aprovação.</DialogDescription></DialogHeader><div className="grid sm:grid-cols-2 gap-4"><div><Label>Nome completo *</Label><Input value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})}/></div><div><Label>WhatsApp com DDD *</Label><Input inputMode="tel" value={form.telefone} onChange={e=>setForm({...form,telefone:e.target.value})} onBlur={()=>setForm({...form,telefone:fmtPhoneBR(normalizeBRPhone(form.telefone))})} placeholder="(65) 99999-9999"/></div><div><Label>Data desejada *</Label><Input type="date" min={ymd(new Date())} value={form.data} onChange={e=>setForm({...form,data:e.target.value})}/></div><div className="grid grid-cols-2 gap-2"><div><Label>Começa</Label><Input type="time" value={form.inicio} onChange={e=>setForm({...form,inicio:e.target.value})}/></div><div><Label>Termina</Label><Input type="time" value={form.fim} onChange={e=>setForm({...form,fim:e.target.value})}/></div></div><div className="sm:col-span-2"><Label>Assunto *</Label><Input value={form.assunto} onChange={e=>setForm({...form,assunto:e.target.value})} placeholder="Ex.: Reunião com associação de moradores"/></div><div><Label>Modalidade</Label><Select value={form.modalidade} onValueChange={v=>setForm({...form,modalidade:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="presencial">Presencial</SelectItem><SelectItem value="online">On-line</SelectItem><SelectItem value="telefone">Telefone</SelectItem></SelectContent></Select></div><div><Label>Local</Label><Input value={form.local} onChange={e=>setForm({...form,local:e.target.value})} placeholder="Bairro, cidade ou endereço"/></div><div><Label>E-mail (opcional)</Label><Input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div><Label>Quantidade de pessoas</Label><Input type="number" min="1" value={form.quantidade} onChange={e=>setForm({...form,quantidade:e.target.value})}/></div><div className="sm:col-span-2"><Label>Conte um pouco mais</Label><Textarea value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})}/></div></div><div className="rounded-lg bg-amber-50 text-amber-900 p-3 text-sm"><Clock className="inline w-4 h-4 mr-1"/><b>Importante:</b> enviar este formulário não reserva automaticamente o horário.</div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Voltar</Button><Button onClick={submit} disabled={sending} style={{backgroundColor:info.cor}}>{sending&&<Loader2 className="animate-spin w-4 h-4 mr-2"/>}Enviar para análise</Button></DialogFooter></DialogContent></Dialog>
  </div>
}
