import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { supabase } from "@/integrations/supabase/client-selfhosted";
export default function EngagementDailySettings({clientId}:{clientId:string}){const [vol,setVol]=useState(false),[hours,setHours]=useState(24),[saving,setSaving]=useState(false);useEffect(()=>{supabase.from("engagement_config" as any).select("incluir_voluntarios_missao,prazo_missao_horas").eq("client_id",clientId).maybeSingle().then(({data}:any)=>{if(data){setVol(!!data.incluir_voluntarios_missao);setHours(data.prazo_missao_horas||24)}})},[clientId]);const save=async()=>{setSaving(true);const {error}=await supabase.from("engagement_config" as any).upsert({client_id:clientId,incluir_voluntarios_missao:vol,prazo_missao_horas:Math.max(1,hours)},{onConflict:"client_id"});setSaving(false);error?toast.error(error.message):toast.success("Configuração salva para as próximas missões.")};return <Card><CardHeader><CardTitle>Configuração das missões diárias</CardTitle><CardDescription>Contratados ativos sempre são obrigados. Alterações valem somente para missões futuras.</CardDescription></CardHeader><CardContent className="space-y-5"><div className="flex items-center justify-between rounded-lg border p-4"><div><Label>Incluir voluntários</Label><p className="text-xs text-muted-foreground">Mantém os voluntários separados, mas também cria obrigação diária para eles.</p></div><Switch checked={vol} onCheckedChange={setVol}/></div><div className="max-w-xs space-y-2"><Label>Prazo padrão da missão, em horas</Label><Input type="number" min={1} value={hours} onChange={e=>setHours(Number(e.target.value))}/></div><Button onClick={save} disabled={saving}>Salvar configuração</Button></CardContent></Card>}
