/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksEleicaoCobrancaAutoRouteImport } from './routes/api/public/hooks/eleicao-cobranca-auto'
import { Route as ApiPublicMMissionIdDCodeRouteImport } from './routes/api/public/m.$missionId.d.$code'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksEleicaoCobrancaAutoRoute =
  ApiPublicHooksEleicaoCobrancaAutoRouteImport.update({
    id: '/api/public/hooks/eleicao-cobranca-auto',
    path: '/api/public/hooks/eleicao-cobranca-auto',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMMissionIdDCodeRoute =
  ApiPublicMMissionIdDCodeRouteImport.update({
    id: '/api/public/m/$missionId/d/$code',
    path: '/api/public/m/$missionId/d/$code',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/public/hooks/eleicao-cobranca-auto': typeof ApiPublicHooksEleicaoCobrancaAutoRoute
  '/api/public/m/$missionId/d/$code': typeof ApiPublicMMissionIdDCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/public/hooks/eleicao-cobranca-auto': typeof ApiPublicHooksEleicaoCobrancaAutoRoute
  '/api/public/m/$missionId/d/$code': typeof ApiPublicMMissionIdDCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/public/hooks/eleicao-cobranca-auto': typeof ApiPublicHooksEleicaoCobrancaAutoRoute
  '/api/public/m/$missionId/d/$code': typeof ApiPublicMMissionIdDCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/api/public/hooks/eleicao-cobranca-auto'
    | '/api/public/m/$missionId/d/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/api/public/hooks/eleicao-cobranca-auto'
    | '/api/public/m/$missionId/d/$code'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/api/public/hooks/eleicao-cobranca-auto'
    | '/api/public/m/$missionId/d/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApiPublicHooksEleicaoCobrancaAutoRoute: typeof ApiPublicHooksEleicaoCobrancaAutoRoute
  ApiPublicMMissionIdDCodeRoute: typeof ApiPublicMMissionIdDCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/eleicao-cobranca-auto': {
      id: '/api/public/hooks/eleicao-cobranca-auto'
      path: '/api/public/hooks/eleicao-cobranca-auto'
      fullPath: '/api/public/hooks/eleicao-cobranca-auto'
      preLoaderRoute: typeof ApiPublicHooksEleicaoCobrancaAutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/m/$missionId/d/$code': {
      id: '/api/public/m/$missionId/d/$code'
      path: '/api/public/m/$missionId/d/$code'
      fullPath: '/api/public/m/$missionId/d/$code'
      preLoaderRoute: typeof ApiPublicMMissionIdDCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApiPublicHooksEleicaoCobrancaAutoRoute:
    ApiPublicHooksEleicaoCobrancaAutoRoute,
  ApiPublicMMissionIdDCodeRoute: ApiPublicMMissionIdDCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
