/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTelemarketingPurgeTestOperatorRouteImport } from './routes/api/telemarketing/purge-test-operator'
import { Route as ApiPublicMissaoSwitchRouteImport } from './routes/api/public/missao/switch'
import { Route as ApiPublicMissaoIdentifyRouteImport } from './routes/api/public/missao/identify'
import { Route as ApiPublicMissaoEventRouteImport } from './routes/api/public/missao/event'
import { Route as ApiPublicHooksEleicaoCobrancaAutoRouteImport } from './routes/api/public/hooks/eleicao-cobranca-auto'
import { Route as ApiPublicMissaoConfigMissionIdRouteImport } from './routes/api/public/missao/config.$missionId'
import { Route as ApiPublicMMissionIdDCodeRouteImport } from './routes/api/public/m.$missionId.d.$code'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelemarketingPurgeTestOperatorRoute =
  ApiTelemarketingPurgeTestOperatorRouteImport.update({
    id: '/api/telemarketing/purge-test-operator',
    path: '/api/telemarketing/purge-test-operator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMissaoSwitchRoute = ApiPublicMissaoSwitchRouteImport.update({
  id: '/api/public/missao/switch',
  path: '/api/public/missao/switch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMissaoIdentifyRoute = ApiPublicMissaoIdentifyRouteImport.update({
  id: '/api/public/missao/identify',
  path: '/api/public/missao/identify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMissaoEventRoute = ApiPublicMissaoEventRouteImport.update({
  id: '/api/public/missao/event',
  path: '/api/public/missao/event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksEleicaoCobrancaAutoRoute =
  ApiPublicHooksEleicaoCobrancaAutoRouteImport.update({
    id: '/api/public/hooks/eleicao-cobranca-auto',
    path: '/api/public/hooks/eleicao-cobranca-auto',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMissaoConfigMissionIdRoute =
  ApiPublicMissaoConfigMissionIdRouteImport.update({
    id: '/api/public/missao/config/$missionId',
    path: '/api/public/missao/config/$missionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMMissionIdDCodeRoute =
  ApiPublicMMissionIdDCodeRouteImport.update({
    id: '/api/public/m/$missionId/d/$code',
    path: '/api/public/m/$missionId/d/$code',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/telemarketing/purge-test-operator': typeof ApiTelemarketingPurgeTestOperatorRoute
  '/api/public/hooks/eleicao-cobranca-auto': typeof ApiPublicHooksEleicaoCobrancaAutoRoute
  '/api/public/missao/event': typeof ApiPublicMissaoEventRoute
  '/api/public/missao/identify': typeof ApiPublicMissaoIdentifyRoute
  '/api/public/missao/switch': typeof ApiPublicMissaoSwitchRoute
  '/api/public/missao/config/$missionId': typeof ApiPublicMissaoConfigMissionIdRoute
  '/api/public/m/$missionId/d/$code': typeof ApiPublicMMissionIdDCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/telemarketing/purge-test-operator': typeof ApiTelemarketingPurgeTestOperatorRoute
  '/api/public/hooks/eleicao-cobranca-auto': typeof ApiPublicHooksEleicaoCobrancaAutoRoute
  '/api/public/missao/event': typeof ApiPublicMissaoEventRoute
  '/api/public/missao/identify': typeof ApiPublicMissaoIdentifyRoute
  '/api/public/missao/switch': typeof ApiPublicMissaoSwitchRoute
  '/api/public/missao/config/$missionId': typeof ApiPublicMissaoConfigMissionIdRoute
  '/api/public/m/$missionId/d/$code': typeof ApiPublicMMissionIdDCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/telemarketing/purge-test-operator': typeof ApiTelemarketingPurgeTestOperatorRoute
  '/api/public/hooks/eleicao-cobranca-auto': typeof ApiPublicHooksEleicaoCobrancaAutoRoute
  '/api/public/missao/event': typeof ApiPublicMissaoEventRoute
  '/api/public/missao/identify': typeof ApiPublicMissaoIdentifyRoute
  '/api/public/missao/switch': typeof ApiPublicMissaoSwitchRoute
  '/api/public/missao/config/$missionId': typeof ApiPublicMissaoConfigMissionIdRoute
  '/api/public/m/$missionId/d/$code': typeof ApiPublicMMissionIdDCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/api/telemarketing/purge-test-operator'
    | '/api/public/hooks/eleicao-cobranca-auto'
    | '/api/public/missao/event'
    | '/api/public/missao/identify'
    | '/api/public/missao/switch'
    | '/api/public/missao/config/$missionId'
    | '/api/public/m/$missionId/d/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/api/telemarketing/purge-test-operator'
    | '/api/public/hooks/eleicao-cobranca-auto'
    | '/api/public/missao/event'
    | '/api/public/missao/identify'
    | '/api/public/missao/switch'
    | '/api/public/missao/config/$missionId'
    | '/api/public/m/$missionId/d/$code'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/api/telemarketing/purge-test-operator'
    | '/api/public/hooks/eleicao-cobranca-auto'
    | '/api/public/missao/event'
    | '/api/public/missao/identify'
    | '/api/public/missao/switch'
    | '/api/public/missao/config/$missionId'
    | '/api/public/m/$missionId/d/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApiTelemarketingPurgeTestOperatorRoute: typeof ApiTelemarketingPurgeTestOperatorRoute
  ApiPublicHooksEleicaoCobrancaAutoRoute: typeof ApiPublicHooksEleicaoCobrancaAutoRoute
  ApiPublicMissaoEventRoute: typeof ApiPublicMissaoEventRoute
  ApiPublicMissaoIdentifyRoute: typeof ApiPublicMissaoIdentifyRoute
  ApiPublicMissaoSwitchRoute: typeof ApiPublicMissaoSwitchRoute
  ApiPublicMissaoConfigMissionIdRoute: typeof ApiPublicMissaoConfigMissionIdRoute
  ApiPublicMMissionIdDCodeRoute: typeof ApiPublicMMissionIdDCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telemarketing/purge-test-operator': {
      id: '/api/telemarketing/purge-test-operator'
      path: '/api/telemarketing/purge-test-operator'
      fullPath: '/api/telemarketing/purge-test-operator'
      preLoaderRoute: typeof ApiTelemarketingPurgeTestOperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/missao/switch': {
      id: '/api/public/missao/switch'
      path: '/api/public/missao/switch'
      fullPath: '/api/public/missao/switch'
      preLoaderRoute: typeof ApiPublicMissaoSwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/missao/identify': {
      id: '/api/public/missao/identify'
      path: '/api/public/missao/identify'
      fullPath: '/api/public/missao/identify'
      preLoaderRoute: typeof ApiPublicMissaoIdentifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/missao/event': {
      id: '/api/public/missao/event'
      path: '/api/public/missao/event'
      fullPath: '/api/public/missao/event'
      preLoaderRoute: typeof ApiPublicMissaoEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/eleicao-cobranca-auto': {
      id: '/api/public/hooks/eleicao-cobranca-auto'
      path: '/api/public/hooks/eleicao-cobranca-auto'
      fullPath: '/api/public/hooks/eleicao-cobranca-auto'
      preLoaderRoute: typeof ApiPublicHooksEleicaoCobrancaAutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/missao/config/$missionId': {
      id: '/api/public/missao/config/$missionId'
      path: '/api/public/missao/config/$missionId'
      fullPath: '/api/public/missao/config/$missionId'
      preLoaderRoute: typeof ApiPublicMissaoConfigMissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/m/$missionId/d/$code': {
      id: '/api/public/m/$missionId/d/$code'
      path: '/api/public/m/$missionId/d/$code'
      fullPath: '/api/public/m/$missionId/d/$code'
      preLoaderRoute: typeof ApiPublicMMissionIdDCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApiTelemarketingPurgeTestOperatorRoute:
    ApiTelemarketingPurgeTestOperatorRoute,
  ApiPublicHooksEleicaoCobrancaAutoRoute:
    ApiPublicHooksEleicaoCobrancaAutoRoute,
  ApiPublicMissaoEventRoute: ApiPublicMissaoEventRoute,
  ApiPublicMissaoIdentifyRoute: ApiPublicMissaoIdentifyRoute,
  ApiPublicMissaoSwitchRoute: ApiPublicMissaoSwitchRoute,
  ApiPublicMissaoConfigMissionIdRoute: ApiPublicMissaoConfigMissionIdRoute,
  ApiPublicMMissionIdDCodeRoute: ApiPublicMMissionIdDCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
