begin;

create table if not exists public.tse_votacao_secao (
  id bigint generated by default as identity primary key,
  ano integer not null,
  turno integer not null default 1,
  pleito integer not null,
  eleicao integer not null,
  uf text not null check (char_length(uf) = 2),
  cod_municipio integer not null,
  municipio text not null,
  zona integer not null,
  secao integer not null,
  secoes_agregadas integer[] not null default '{}',
  nr_local integer not null,
  cargo integer not null check (cargo in (6, 7)),
  numero integer not null,
  partido_numero integer,
  votos integer not null default 0 check (votos >= 0),
  tse_hash text,
  source text not null default 'resultados_tse_bu',
  updated_at timestamptz not null default now(),
  constraint tse_votacao_secao_natural_key
    unique (ano, turno, cod_municipio, zona, secao, cargo, numero)
);

create index if not exists idx_tse_secao_candidate_city
  on public.tse_votacao_secao
  (ano, uf, cod_municipio, cargo, numero, zona, secao)
  include (votos, nr_local, secoes_agregadas);

create index if not exists idx_tse_secao_local
  on public.tse_votacao_secao
  (ano, cod_municipio, zona, nr_local);

alter table public.tse_votacao_secao enable row level security;
revoke all on table public.tse_votacao_secao from public, anon;
grant select on table public.tse_votacao_secao to authenticated;

drop policy if exists "Authenticated users read official TSE section votes"
  on public.tse_votacao_secao;
create policy "Authenticated users read official TSE section votes"
  on public.tse_votacao_secao
  for select
  to authenticated
  using (true);

create table if not exists public.tse_secao_sync_status (
  ano integer not null,
  turno integer not null default 1,
  uf text not null check (char_length(uf) = 2),
  cod_municipio integer not null,
  municipio text not null,
  status text not null default 'pending'
    check (status in ('pending', 'running', 'partial', 'success', 'error')),
  total_secoes integer not null default 0,
  secoes_principais integer not null default 0,
  secoes_processadas integer not null default 0,
  proximo_cursor integer not null default 0,
  erro text,
  updated_at timestamptz not null default now(),
  primary key (ano, turno, uf, cod_municipio)
);

alter table public.tse_secao_sync_status enable row level security;
revoke all on table public.tse_secao_sync_status from public, anon;
grant select on table public.tse_secao_sync_status to authenticated;

drop policy if exists "Authenticated users read TSE section sync status"
  on public.tse_secao_sync_status;
create policy "Authenticated users read TSE section sync status"
  on public.tse_secao_sync_status
  for select
  to authenticated
  using (true);

create or replace function public.get_tse_candidate_sections(
  p_ano integer,
  p_uf text,
  p_cod_municipio integer,
  p_cargo text,
  p_numero integer
)
returns table (
  zona integer,
  secao integer,
  secoes_agregadas integer[],
  nr_local integer,
  nome_local text,
  endereco text,
  bairro text,
  votos integer,
  percentual numeric
)
language sql
stable
security invoker
set search_path = ''
as $$
  with locais as (
    select
      l.cod_municipio,
      l.zona,
      l.nr_local,
      max(l.nome_local) as nome_local,
      max(l.endereco) as endereco,
      max(nullif(btrim(l.bairro), '')) as bairro
    from public.tse_votacao_local l
    where l.cod_municipio = p_cod_municipio
      and l.ano = 2024
    group by l.cod_municipio, l.zona, l.nr_local
  ), catalogo as (
    select distinct
      s.cod_municipio,
      s.zona,
      s.secao,
      s.secoes_agregadas,
      s.nr_local
    from public.tse_votacao_secao s
    where s.ano = p_ano
      and s.uf = upper(p_uf)
      and s.cod_municipio = p_cod_municipio
      and s.cargo = case p_cargo
        when 'Deputado Federal' then 6
        when 'Deputado Estadual' then 7
        else 0
      end
  ), secoes as (
    select
      c.zona,
      c.secao,
      c.secoes_agregadas,
      c.nr_local,
      l.nome_local,
      l.endereco,
      l.bairro,
      coalesce(s.votos, 0)::integer as votos,
      sum(coalesce(s.votos, 0)) over () as total_votos
    from catalogo c
    left join public.tse_votacao_secao s
      on s.ano = p_ano
     and s.uf = upper(p_uf)
     and s.cod_municipio = p_cod_municipio
     and s.zona = c.zona
     and s.secao = c.secao
     and s.cargo = case p_cargo
       when 'Deputado Federal' then 6
       when 'Deputado Estadual' then 7
       else 0
     end
     and s.numero = p_numero
    left join locais l
      on l.cod_municipio = c.cod_municipio
     and l.zona = c.zona
     and l.nr_local = c.nr_local
  )
  select
    s.zona,
    s.secao,
    s.secoes_agregadas,
    s.nr_local,
    s.nome_local,
    s.endereco,
    s.bairro,
    s.votos,
    case
      when s.total_votos > 0
        then round((s.votos::numeric / s.total_votos::numeric) * 100, 4)
      else 0::numeric
    end as percentual
  from secoes s
  order by s.votos desc, s.zona, s.secao;
$$;

revoke all on function public.get_tse_candidate_sections(integer, text, integer, text, integer)
  from public, anon;
grant execute on function public.get_tse_candidate_sections(integer, text, integer, text, integer)
  to authenticated;

create or replace function public.get_tse_municipality_options(
  p_ano integer,
  p_uf text
)
returns table (
  cod_municipio integer,
  municipio text
)
language sql
stable
security invoker
set search_path = ''
as $$
  select t.cod_municipio, max(t.municipio) as municipio
  from public.tse_votacao_zona t
  where t.ano = p_ano
    and t.uf = upper(p_uf)
  group by t.cod_municipio
  order by max(t.municipio);
$$;

revoke all on function public.get_tse_municipality_options(integer, text)
  from public, anon;
grant execute on function public.get_tse_municipality_options(integer, text)
  to authenticated;

commit;
